import Foundation

/// OpenAI-compatible chat message generated by ContextCompiler and consumed
/// by the transport client.
struct ChatMessage: Codable, Sendable, Equatable {
    let role: String
    let content: String
}
