import Foundation

/// OpenAI-compatible chat message generated by ContextCompiler and consumed
/// by the transport client. Supports text-only messages plus assistant tool
/// calls and tool-result messages.
struct ChatMessage: Codable, Sendable, Equatable {
    let role: String
    let content: String?
    let toolCalls: [ToolCall]?
    let toolCallID: String?

    init(role: String, content: String) {
        self.role = role
        self.content = content
        self.toolCalls = nil
        self.toolCallID = nil
    }

    init(role: String, content: String?, toolCalls: [ToolCall]? = nil, toolCallID: String? = nil) {
        self.role = role
        self.content = content
        self.toolCalls = toolCalls
        self.toolCallID = toolCallID
    }

    static func assistantToolCalls(_ calls: [ToolCall], content: String? = nil) -> ChatMessage {
        ChatMessage(role: "assistant", content: content, toolCalls: calls)
    }

    static func toolResult(toolCallID: String, content: String) -> ChatMessage {
        ChatMessage(role: "tool", content: content, toolCallID: toolCallID)
    }

    enum CodingKeys: String, CodingKey {
        case role
        case content
        case toolCalls = "tool_calls"
        case toolCallID = "tool_call_id"
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        if let content {
            try container.encode(content, forKey: .content)
        } else if role == "assistant", toolCalls != nil {
            try container.encodeNil(forKey: .content)
        }
        try container.encodeIfPresent(toolCalls, forKey: .toolCalls)
        try container.encodeIfPresent(toolCallID, forKey: .toolCallID)
    }
}
